from __future__ import annotations

UNIFIED = [
    ("dairy", "Молочні продукти та яйця"),
    ("meat", "М'ясо та ковбаси"),
    ("fish", "Риба та морепродукти"),
    ("fruits", "Фрукти та овочі"),
    ("bakery", "Хліб та випічка"),
    ("grocery", "Бакалія"),
    ("frozen", "Заморозка"),
    ("canned", "Консерви"),
    ("sauces", "Соуси та спеції"),
    ("sweets", "Солодощі"),
    ("snacks", "Чипси та снеки"),
    ("drinks", "Напої"),
    ("hot_drinks", "Чай, кава, какао"),
    ("alcohol", "Алкоголь"),
    ("tobacco", "Тютюнові вироби"),
    ("hygiene", "Гігієна та догляд"),
    ("household", "Побутова хімія"),
    ("home", "Товари для дому"),
    ("kitchen", "Кухня та посуд"),
    ("kids", "Дитячі товари"),
    ("pets", "Товари для тварин"),
    ("hobby", "Хобі та відпочинок"),
    ("health", "Здоров'я та аптека"),
    ("other", "Інше"),
]

UNIFIED_DICT = dict(UNIFIED)

# Silpo: category slug → unified slug
_SILPO_MAP = {
    # Dairy
    "yogurty-245": "dairy",
    "moloko-253": "dairy",
    "smetana-4376": "dairy",
    "vershky-257": "dairy",
    "kuriachi-iaitsia-4977": "dairy",
    "maslo-4980": "dairy",
    "margaryn-4981": "dairy",
    "spred-4982": "dairy",
    "kefir-riazhanka-airan-4984": "dairy",
    "napoi-na-syrovattsi-4985": "dairy",
    "zakvaska-4986": "dairy",
    "syr-kyslomolochnyi-4988": "dairy",
    "syrkova-masa-4989": "dairy",
    "molochni-i-syrkovi-deserty-4990": "dairy",
    "molochni-pudyngy-i-zhele-4991": "dairy",
    "glazurovani-syrky-4992": "dairy",
    "zghushchene-moloko-4993": "dairy",
    "moloko-dlia-ditei-4995": "dairy",
    "kyslomolochni-napoi-dlia-ditei-4996": "dairy",
    "bezlaktozna-molochna-produktsiia-5000": "dairy",
    "bezmolochna-produktsiia-240": "dairy",
    "syry-z-plisniavoiu-5002": "dairy",
    "krem-syry-5005": "dairy",
    "syry-rozsilni-feta-motsarela-inshi-5006": "dairy",
    "syry-plavleni-5007": "dairy",
    "vytrymani-parmezan-gauda-chedder-inshi-5011": "dairy",
    "krupnoporysti-maasdam-radamer-inshi-5012": "dairy",
    "napivtverdi-tenero-vershkovyi-inshi-5013": "dairy",
    "syry-spetsialitety-5014": "dairy",
    "nabory-syriv-1470": "dairy",
    "biskvity-molochni-241": "dairy",
    # Meat
    "svynyna-4413": "meat",
    "yalovychyna-ta-teliatyna-4414": "meat",
    "baranyna-ta-iagniatyna-4415": "meat",
    "kroliatyna-4416": "meat",
    "farsh-4419": "meat",
    "salo-4420": "meat",
    "subprodukty-4421": "meat",
    "m-iasni-napivfabrykaty-4422": "meat",
    "m-iaso-dlia-shashlyka-ta-barbekiu-4423": "meat",
    "kuriatyna-4426": "meat",
    "indychatyna-4427": "meat",
    "kachatyna-ta-gusiatyna-4428": "meat",
    "perepilka-4429": "meat",
    "varena-kovbasa-4736": "meat",
    "kopchena-kovbasa-4737": "meat",
    "syrov-ialena-syrokopchena-kovbasa-4738": "meat",
    "zapechena-kovbasa-4739": "meat",
    "krov-ianka-i-liverna-kovbasa-4740": "meat",
    "kovbasky-4741": "meat",
    "sosysky-4733": "meat",
    "sardelky-4734": "meat",
    "shynka-4745": "meat",
    "grudynka-i-bekon-4746": "meat",
    "m-iasni-rulety-4747": "meat",
    "shyika-kopchena-4749": "meat",
    "khamon-4756": "meat",
    "basturma-4750": "meat",
    "pashtety-ta-namazky-4751": "meat",
    "kopchenosti-4752": "meat",
    "zelts-saltyson-iazyk-4753": "meat",
    "balyk-4743": "meat",
    "buzhenyna-4744": "meat",
    "m-iaso-kovbasna-narizka-4759": "meat",
    "m-iasni-sneky-4758": "meat",
    "m-iasni-chypsy-i-sneky-5030": "meat",
    "m-iasni-stravy-4767": "meat",
    "m-iasni-ta-ovochevi-napivfabrykaty-5169": "meat",
    "burgery-i-sendvichi-4776": "meat",
    # Fish
    "zamorozhena-ryba-4432": "fish",
    "zamorozheni-moreprodukty-ta-moliusky-4451": "fish",
    "zamorozheni-ravlyky-4440": "fish",
    "okholodzheni-moreprodukty-ta-moliusky-4450": "fish",
    "kopchena-ryba-ta-moreprodukty-4442": "fish",
    "slabosolena-ryba-4441": "fish",
    "v-ialena-ta-sushena-ryba-4443": "fish",
    "preservy-rybni-4444": "fish",
    "krabovi-palychky-4438": "fish",
    "chervona-ikra-4445": "fish",
    "ikra-inshykh-ryb-4447": "fish",
    "rybni-zakusky-4452": "fish",
    "morska-kapusta-ta-salaty-4453": "fish",
    "losos-i-forel-4858": "fish",
    "morska-ryba-4859": "fish",
    "rybni-napivfabrykaty-4434": "fish",
    "rybni-pasty-4586": "fish",
    "rybni-sneky-5029": "fish",
    "rybni-stravy-4768": "fish",
    # Fruits & vegetables
    "banany-4792": "fruits",
    "vynograd-4793": "fruits",
    "kavuny-i-dyni-4796": "fruits",
    "kivi-4797": "fruits",
    "kokos-4798": "fruits",
    "mango-4799": "fruits",
    "persyky-abrykosy-slyvy-4800": "fruits",
    "tropichni-frukty-4802": "fruits",
    "tsytrusovi-4804": "fruits",
    "yabluka-4805": "fruits",
    "yagody-4806": "fruits",
    "smuzi-i-freshi-4807": "fruits",
    "granat-4794": "fruits",
    "grushi-4795": "fruits",
    "kartoplia-i-batat-4817": "fruits",
    "kapusta-4813": "fruits",
    "morkva-4818": "fruits",
    "ogirky-4823": "fruits",
    "perets-4824": "fruits",
    "pomidory-4825": "fruits",
    "tsybulia-i-chasnyk-4826": "fruits",
    "buriak-4819": "fruits",
    "garbuz-4812": "fruits",
    "sparzha-4814": "fruits",
    "redyska-redka-koreneplody-4820": "fruits",
    "bazylik-4833": "fruits",
    "zelena-tsybulia-4834": "fruits",
    "zelen-miks-4835": "fruits",
    "krip-4837": "fruits",
    "m-iata-4838": "fruits",
    "petrushka-4839": "fruits",
    "priani-travy-4840": "fruits",
    "salaty-4831": "fruits",
    "selera-4841": "fruits",
    "shpynat-4843": "fruits",
    "shchavel-4844": "fruits",
    "mikrogrin-4830": "fruits",
    "pecherytsi-4850": "fruits",
    "ekzotychni-gryby-4848": "fruits",
    "susheni-gryby-4851": "fruits",
    "gorikhy-4854": "fruits",
    "nasinnia-i-zerniata-4855": "fruits",
    "sukhofrukty-i-tsukaty-4856": "fruits",
    "sumishi-gorikhiv-i-sukhofruktiv-4857": "fruits",
    "fruktovi-ovochevi-sneky-4790": "fruits",
    # Bakery
    "khlib-5139": "bakery",
    "baton-5140": "bakery",
    "baget-5143": "bakery",
    "bulky-5144": "bakery",
    "bulochky-i-pyrizhky-5146": "bakery",
    "lavash-tortylia-5145": "bakery",
    "kruasany-5148": "bakery",
    "pampukhy-donaty-churrosy-5147": "bakery",
    "vypichka-z-lystkovogo-tista-5149": "bakery",
    "zdobna-vypichka-5150": "bakery",
    "pyrogy-i-tarty-5152": "bakery",
    "keksy-i-mafiny-5153": "bakery",
    "syrnyky-5155": "bakery",
    "khlibtsi-5166": "bakery",
    "grissini-ta-khlibni-palychky-5165": "bakery",
    "solomka-5164": "bakery",
    "prianyky-5167": "bakery",
    "torty-5045": "bakery",
    "tistechka-5047": "bakery",
    "panetone-sviatkovi-keksy-5082": "bakery",
    "pyrogy-pyrizhky-vypichka-4784": "bakery",
    "napivfabrykaty-vlasnogo-vyrobnytstva-4785": "bakery",
    # Grocery
    "rys-4873": "grocery",
    "grechka-4872": "grocery",
    "vivsiana-krupa-4877": "grocery",
    "pshenychna-krupa-4874": "grocery",
    "bulgur-4875": "grocery",
    "kuskus-4876": "grocery",
    "inshi-krupy-4880": "grocery",
    "bobovi-4879": "grocery",
    "makarony-4884": "grocery",
    "pshenychne-boroshno-4889": "grocery",
    "vivsiane-boroshno-4893": "grocery",
    "rysove-boroshno-4894": "grocery",
    "grechane-boroshno-4892": "grocery",
    "bezghliutenove-boroshno-4897": "grocery",
    "inshi-vydy-boroshna-4895": "grocery",
    "sumishi-dlia-vypichky-4898": "grocery",
    "sil-4901": "grocery",
    "tsukor-4902": "grocery",
    "tsukrova-pudra-4969": "grocery",
    "soniashnykova-oliia-4905": "grocery",
    "olyvkova-oliia-4906": "grocery",
    "inshi-olii-4907": "grocery",
    "otset-4908": "grocery",
    "sik-kontsentrat-4909": "grocery",
    "plastivtsi-4925": "grocery",
    "miusli-i-granola-4926": "grocery",
    "gotovi-snidanky-4927": "grocery",
    "kashi-4928": "grocery",
    "lokshyna-4929": "grocery",
    "supy-i-piure-4930": "grocery",
    "rys-ta-lokshyna-4934": "grocery",
    "nabory-dlia-prygotuvannia-4937": "grocery",
    "aziiski-stravy-shvydkogo-prygotuvannia-4936": "grocery",
    "paniruvannia-4943": "grocery",
    "drizhdzhi-4966": "grocery",
    "lymonna-kyslota-4967": "grocery",
    "krokhmal-zagushchuvach-4974": "grocery",
    "soda-i-rozpushuvach-4965": "grocery",
    "vysivky-5015": "grocery",
    "superfudy-4878": "grocery",
    "krem-dlia-vypichky-4971": "grocery",
    "nachynky-i-posypky-4968": "grocery",
    "zagotovky-dlia-desertiv-4975": "grocery",
    "prypravy-do-vypichky-4972": "grocery",
    "kysil-zhele-pudyngy-4973": "grocery",
    # Frozen
    "morozyvo-5177": "frozen",
    "pelmeni-5170": "frozen",
    "varenyky-5171": "frozen",
    "varenyky-pelmeni-giozy-khinkali-4771": "frozen",
    "khinkali-i-ravioli-5192": "frozen",
    "mlyntsi-zamorozheni-5173": "frozen",
    "syrnyky-zamorozheni-5174": "frozen",
    "gotovi-stravy-zamorozheni-5175": "frozen",
    "deserty-i-torty-zamorozheni-5178": "frozen",
    "ovochi-zamorozheni-5184": "frozen",
    "yagody-zamorozheni-5186": "frozen",
    "sneky-zamorozheni-5182": "frozen",
    "vypichka-zamorozhena-5172": "frozen",
    "tisto-zamorozhene-274": "frozen",
    "lid-267": "frozen",
    "pitsa-4775": "frozen",
    # Canned
    "olyvky-4916": "canned",
    "goroshok-kukurudza-4914": "canned",
    "m-iasna-4911": "canned",
    "rybna-4912": "canned",
    "ovocheva-4913": "canned",
    "grybna-4915": "canned",
    "fruktova-konservatsiia-4919": "canned",
    "kapersy-artyshoky-zakusky-4917": "canned",
    "solinnia-4852": "canned",
    "marynovani-stravy-4781": "canned",
    # Sauces & spices
    "sousy-4949": "sauces",
    "sousy-dlia-pasty-4887": "sauces",
    "sousy-prypravy-4932": "sauces",
    "soievyi-sous-4976": "sauces",
    "ketchup-4948": "sauces",
    "maionez-4951": "sauces",
    "girchytsia-4955": "sauces",
    "adzhyka-4950": "sauces",
    "zapravky-4952": "sauces",
    "tomatna-pasta-i-piure-4954": "sauces",
    "spetsii-i-travy-4959": "sauces",
    "universalni-prypravy-4960": "sauces",
    "perets-i-sumishi-pertsiv-4957": "sauces",
    "lavrovyi-lyst-4958": "sauces",
    "aromatyzatory-4964": "sauces",
    "susheni-ovochi-4961": "sauces",
    "sousy-do-syriv-4728": "sauces",
    # Sweets
    "shokolad-plytka-523": "sweets",
    "shokoladni-batonchyky-525": "sweets",
    "shokoladni-tsukerky-5056": "sweets",
    "shokoladni-figurky-5051": "sweets",
    "shokoladni-figurky-524": "sweets",
    "shokoladni-iaitsia-526": "sweets",
    "shokolad-ruchnoi-roboty-5048": "sweets",
    "tsukerky-v-korobtsi-5057": "sweets",
    "tsukerky-ruchnoi-roboty-5049": "sweets",
    "pomadni-tsukerky-i-irysky-5058": "sweets",
    "frukty-v-shokoladi-5060": "sweets",
    "drazhe-5050": "sweets",
    "drazhe-5061": "sweets",
    "lodianyky-5062": "sweets",
    "zheleni-tsukerky-5063": "sweets",
    "pechyvo-5053": "sweets",
    "pechyvo-5065": "sweets",
    "vafli-5066": "sweets",
    "krekery-5068": "sweets",
    "biskvity-rulety-keksy-5067": "sweets",
    "keksy-i-rulety-5046": "sweets",
    "marmelad-5071": "sweets",
    "marmelad-i-zefir-5052": "sweets",
    "zefir-5069": "sweets",
    "pastyla-5072": "sweets",
    "khalva-516": "sweets",
    "nuga-515": "sweets",
    "lukum-514": "sweets",
    "pakhlava-519": "sweets",
    "kozynaky-513": "sweets",
    "varennia-ta-dzhemy-4921": "sweets",
    "med-4922": "sweets",
    "pasty-shokoladno-gorikhovi-4920": "sweets",
    "syropy-i-topingy-4923": "sweets",
    "gorikhy-v-syropi-517": "sweets",
    "batonchyky-5040": "sweets",
    "torty-5054": "sweets",
    "tistechka-5055": "sweets",
    "podarunkovi-tsukerky-5085": "sweets",
    "podarunkove-pechyvo-i-prianyky-5086": "sweets",
    "zheleini-tsukerky-5063": "sweets",
    "zhuvalna-gumka-5075": "sweets",
    # Snacks
    "kartopliani-chypsy-5021": "snacks",
    "zlakovi-chypsy-5022": "snacks",
    "ovochevi-chypsy-5020": "snacks",
    "fruktovi-chypsy-5019": "snacks",
    "chypsy-z-nori-5018": "snacks",
    "sukharyky-i-grinky-5024": "snacks",
    "solomka-solona-5027": "snacks",
    "soloni-gorishky-5032": "snacks",
    "soniashnykove-nasinnia-5034": "snacks",
    "garbuzove-nasinnia-5035": "snacks",
    "kukurudziani-palychky-5037": "snacks",
    "popkorn-5038": "snacks",
    "smazhena-kukurudza-5039": "snacks",
    "syrni-sneky-5031": "snacks",
    # Drinks
    "soky-5102": "drinks",
    "sokovmisni-napoi-5106": "drinks",
    "nektary-5104": "drinks",
    "morsy-5107": "drinks",
    "solodka-voda-gazovana-5095": "drinks",
    "solodka-voda-negazovana-5099": "drinks",
    "smakova-voda-5092": "drinks",
    "negazovana-voda-5088": "drinks",
    "slabogazovana-voda-5089": "drinks",
    "sylnogazovana-voda-5090": "drinks",
    "energetychni-napoi-59": "drinks",
    "kvas-57": "drinks",
    "kombucha-i-fermentovani-napoi-5109": "drinks",
    "kholodni-chai-ta-kava-58": "drinks",
    "soky-i-napoi-dytiachi-4681": "drinks",
    "dytiache-shampanske-5100": "drinks",
    # Hot drinks
    "kava-v-zernakh-5111": "hot_drinks",
    "kava-v-kapsulakh-5112": "hot_drinks",
    "kava-vlasnogo-obsmazhennia-5113": "hot_drinks",
    "kava-melena-5114": "hot_drinks",
    "kava-rozchynna-5115": "hot_drinks",
    "kava-u-stikakh-5116": "hot_drinks",
    "drip-kava-5117": "hot_drinks",
    "kakao-gariachyi-shokolad-360": "hot_drinks",
    "tsykorii-369": "hot_drinks",
    "chornyi-chai-5128": "hot_drinks",
    "zelenyi-chai-5127": "hot_drinks",
    "trav-iani-fruktovi-plodovi-chai-5129": "hot_drinks",
    "osoblyvi-chai-5130": "hot_drinks",
    "chai-vagovyi-5132": "hot_drinks",
    "chaini-nabory-ta-asorti-5133": "hot_drinks",
    "sumishi-chaiv-5134": "hot_drinks",
    # Alcohol
    "chervoni-vyna-4475": "alcohol",
    "bili-vyna-4476": "alcohol",
    "rozhevi-vyna-4502": "alcohol",
    "pomaranchevi-vyna-4477": "alcohol",
    "plodovo-iagidni-vyna-4479": "alcohol",
    "kripleni-vyna-kheres-kagor-ta-in-4501": "alcohol",
    "bezalkogolne-vyno-4483": "alcohol",
    "igrysti-vyna-ta-shampanske-4460": "alcohol",
    "vermuty-4461": "alcohol",
    "sangriia-ta-glintvein-4478": "alcohol",
    "viski-4466": "alcohol",
    "koniak-brendi-4467": "alcohol",
    "rom-4468": "alcohol",
    "dzhyn-4469": "alcohol",
    "tekila-agavovi-dystyliaty-4470": "alcohol",
    "gorilka-4472": "alcohol",
    "nastoianky-nalyvky-4473": "alcohol",
    "likery-balzamy-bittery-4474": "alcohol",
    "aziiskyi-alkogol-4471": "alcohol",
    "importne-pyvo-4505": "alcohol",
    "ukrainske-pyvo-4504": "alcohol",
    "kraftove-pyvo-4506": "alcohol",
    "vlasna-brovarnia-beermaster-brewery-4507": "alcohol",
    "bezalkogolne-pyvo-4484": "alcohol",
    "sydr-ta-zbyten-4480": "alcohol",
    "slaboalkogolni-kokteili-4482": "alcohol",
    "alkoenergetyky-4481": "alcohol",
    "bezalkogolni-kokteili-4486": "alcohol",
    "bezalkogolni-mitsni-napoi-4485": "alcohol",
    # Hygiene & care
    "shampuni-4548": "hygiene",
    "kondytsionery-dlia-volossia-4549": "hygiene",
    "masky-dlia-volossia-4550": "hygiene",
    "zasoby-dlia-ukladky-4551": "hygiene",
    "spetsialnyi-dogliad-4553": "hygiene",
    "aksesuary-dlia-volossia-4554": "hygiene",
    "farba-dlia-volossia-4555": "hygiene",
    "geli-dlia-dushu-4536": "hygiene",
    "krem-dlia-tila-4537": "hygiene",
    "skrab-dlia-tila-4541": "hygiene",
    "mylo-4538": "hygiene",
    "mochalky-dlia-dushu-4539": "hygiene",
    "pina-sil-bombochky-dlia-vanny-4540": "hygiene",
    "dezodoranty-4542": "hygiene",
    "krem-i-syrovatka-dlia-oblychchia-4545": "hygiene",
    "dlia-vmyvannia-i-demakiiazhu-4546": "hygiene",
    "kosmetyka-4578": "hygiene",
    "kosmetychni-masky-4587": "hygiene",
    "krem-dlia-ruk-i-nig-4556": "hygiene",
    "dogliad-za-gubamy-4544": "hygiene",
    "sontsezakhysni-zasoby-4521": "hygiene",
    "zubna-pasta-ta-opoliskuvachi-4566": "hygiene",
    "zubni-shchitky-ta-nytka-4567": "hygiene",
    "elektrychni-zubni-shchitky-4568": "hygiene",
    "brytvy-i-leza-4561": "hygiene",
    "zasoby-dlia-golinnia-4562": "hygiene",
    "zasoby-pislia-golinnia-4563": "hygiene",
    "dogliad-za-borodoiu-i-vusamy-4565": "hygiene",
    "prokladky-tampony-dlia-intymnoi-gigiieny-4569": "hygiene",
    "dlia-intymnogo-zhyttia-4572": "hygiene",
    "pidguzky-dlia-doroslykh-4570": "hygiene",
    "vatni-dysky-ta-palychky-4571": "hygiene",
    "vologi-servetky-4574": "hygiene",
    "nosovi-servetky-4575": "hygiene",
    "servetky-v-korobtsi-4576": "hygiene",
    "antyseptyky-masky-plastyri-inshe-4573": "hygiene",
    "kolgotky-4646": "hygiene",
    "shkarpetky-4647": "hygiene",
    "asksesuary-dlia-dogliadu-4698": "hygiene",
    # Household chemicals
    "pralni-poroshky-geli-kapsuly-4589": "household",
    "opoliskuvachi-dlia-bilyzny-4590": "household",
    "pliamovyvidnyky-vidbiliuvachi-4591": "household",
    "dlia-myttia-posudu-4592": "household",
    "dlia-prybyrannia-4593": "household",
    "osvizhuvachi-povitria-4594": "household",
    "aromadyfuzory-4595": "household",
    "insektytsydy-4596": "household",
    "dogliad-za-vzuttiam-4597": "household",
    "dogliad-za-odiagom-i-vzuttiam-4607": "household",
    "guberny-skrebky-rukavychky-ganchirky-4602": "household",
    "gubky-skrebky-rukavychky-ganchirky-4602": "household",
    "inventar-dlia-prybyrannia-4603": "household",
    "pakety-dlia-smittia-4600": "household",
    "gospodarchi-dribnytsi-4601": "household",
    "aksesuary-dlia-vanny-i-tualetu-4599": "household",
    # Home
    "tualetnyi-papir-4612": "home",
    "paperovi-rushnyky-4614": "home",
    "servetky-stolovi-4613": "home",
    "folga-pergament-kharchova-plivka-4604": "home",
    "dlia-zberigannia-produktiv-4643": "home",
    "pakety-sumky-ekotorbynky-4609": "home",
    "filtry-i-kartrydzhi-dlia-vody-4608": "home",
    "batareiky-lampochky-likhtaryky-4605": "home",
    "zapalnychky-sirnyky-4606": "home",
    "svichky-i-pidsvichnyky-4630": "home",
    "vazy-kartyny-i-dekor-4631": "home",
    "domashnii-tekstyl-4644": "home",
    "pobutova-tekhnika-i-elektronika-4652": "home",
    # Kitchen
    "skovoridky-kastruli-4639": "kitchen",
    "tarilky-mysky-i-salatnyky-4634": "kitchen",
    "tarilky-4621": "kitchen",
    "chashky-kelykhy-sklianky-4637": "kitchen",
    "sklianky-4619": "kitchen",
    "kukhonne-nachynnia-4641": "kitchen",
    "kukhonni-nozhi-4640": "kitchen",
    "stolovi-prybory-4636": "kitchen",
    "nabory-posudu-4622": "kitchen",
    "formy-dlia-vypikannia-4638": "kitchen",
    "barni-aksesuary-4642": "kitchen",
    "dlia-prygotuvannia-chaiu-kavy-4635": "kitchen",
    "lozhky-vydelky-mishalky-nozhi-4620": "kitchen",
    "solomynky-i-shpazhky-4627": "kitchen",
    # Kids
    "igrashky-4697": "kids",
    "igrashky-dlia-naimenshykh-4693": "kids",
    "m-iaki-igrashky-4696": "kids",
    "konstruktory-4695": "kids",
    "dytiacha-tvorchist-ta-igry-4694": "kids",
    "dytiachi-knygy-4691": "kids",
    "rozvagy-na-svizhomu-povitri-4689": "kids",
    "pidguzky-4704": "kids",
    "pidguzky-trusyky-4705": "kids",
    "peliushky-4703": "kids",
    "piure-dytiachi-4677": "kids",
    "kashi-dytiachi-4679": "kids",
    "sumishi-dytiachi-4678": "kids",
    "supchyky-dytiachi-4680": "kids",
    "pechyvo-i-sneky-dytiachi-4682": "kids",
    "dytiache-kupannia-4701": "kids",
    "dogliad-za-zubkamy-4702": "kids",
    "kremy-oliiky-prysypky-4700": "kids",
    "dytiachi-vologi-servertky-4671": "kids",
    "aksesuary-dlia-goduvannia-4706": "kids",
    "dytiachyi-posud-4707": "kids",
    "dytiachi-sosky-i-pustushky-4708": "kids",
    "dytiachi-pliashechky-i-poilnyky-4709": "kids",
    "tovary-dlia-mam-4675": "kids",
    # Pets
    "korm-dlia-kotiv-4711": "pets",
    "aksesuary-ta-igrashky-dlia-kotiv-4713": "pets",
    "napovniuvachi-i-kotiachi-tualety-4712": "pets",
    "korm-dlia-sobak-4715": "pets",
    "aksesuary-ta-igrashky-dlia-sobak-4716": "pets",
    "gruming-4727": "pets",
    # Hobby
    "dlia-turyzmu-i-sportu-4666": "hobby",
    "mangaly-i-reshitky-dlia-gryliu-4664": "hobby",
    "vugillia-drova-rozpaliuvachi-4665": "hobby",
    "tovary-dlia-sadu-ta-gorodu-478": "hobby",
    "gorshchyky-dlia-kvitiv-i-aksesuary-4500": "hobby",
    "knygy-4661": "hobby",
    "ruchky-olivtsi-markery-4654": "hobby",
    "zoshyty-notatnyky-albomy-4657": "hobby",
    "papir-4656": "hobby",
    "kantseliarski-aksesuary-4655": "hobby",
    "penaly-portfeli-rantsi-vizytnytsi-4658": "hobby",
    "dytiachi-kantstovary-4659": "hobby",
    # Health
    "vitaminy-5231": "health",
    "mineraly-5232": "health",
    "kompleksy-vitaminiv-i-mineraliv-5233": "health",
    "multyvitaminy-5236": "health",
    "omega-5235": "health",
    "magnii-5244": "health",
    "vitaminy-dlia-volossia-shkiry-nigtiv-5245": "health",
    "vitaminy-dlia-ditei-5259": "health",
    "kolagen-5246": "health",
    "aminokysloty-5248": "health",
    "protein-5249": "health",
    "peredtrenuvalni-kompleksy-5251": "health",
    "fermenty-5237": "health",
    "sorbenty-5238": "health",
    "melatonin-i-kompleksy-dlia-snu-5243": "health",
    "bady-dlia-energii-5256": "health",
    "bady-dlia-sertsia-i-sudyn-5254": "health",
    "dlia-detoksu-i-pidtrymky-pechinky-5239": "health",
    "dlia-kistok-i-suglobiv-5250": "health",
    "diietychne-kharchuvannia-5001": "health",
    # Other / mixed
    "podarunkovi-nabory-4529": "other",
    "tematychni-sviata-4626": "other",
    "dlia-dniv-narodzhen-i-vechirok-4624": "other",
    "podarunkova-upakovka-lystivky-4625": "other",
    "odiag-i-aksesuary-4645": "other",
    "vzuttia-i-domashni-kaptsi-4648": "other",
    "golovni-ubory-i-aksesuary-4650": "other",
    "valizy-i-sumky-4649": "other",
    "dlia-avtomobiliv-4610": "other",
    # Culinary / ready meals
    "salaty-4779": "bakery",
    "pershi-stravy-4765": "bakery",
    "deserty-4786": "bakery",
    "garniry-4769": "bakery",
    "gryl-4770": "bakery",
    "mlyntsi-4763": "bakery",
    "syrnyky-i-zapikanky-4764": "bakery",
    "snidanky-ta-kompleksni-obidy-4783": "bakery",
}

# Novus: category title (or parent title) → unified slug (novus.ua GraphQL titles)
_NOVUS_MAP = {
    # Top-level
    "Яйця та молочні продукти": "dairy",
    "М'ясо та ковбасні вироби": "meat",
    "М'ясо та ковбасні вироби ": "meat",
    "Риба та морепродукти": "fish",
    "Фрукти та овочі": "fruits",
    "Пекарня": "bakery",
    "Бакалія": "grocery",
    "Заморозка": "frozen",
    "Консерви": "canned",
    "Соуси та спеції": "sauces",
    "Солодощі": "sweets",
    "Чипси та снеки": "snacks",
    "Напої": "drinks",
    "Гарячі напої": "hot_drinks",
    "Алкоголь": "alcohol",
    "Алкоголь ": "alcohol",
    "Гігієна та догляд": "hygiene",
    "Побутова хімія": "household",
    "Товари для дому": "home",
    "Інтер'єр та текстиль": "home",
    "Кухня": "kitchen",
    "Кулінарія": "bakery",
    "Товари для дітей": "kids",
    "Товари для тварин": "pets",
    "Хобі та відпочинок": "hobby",
    "Здорове харчування та спосіб життя": "health",
    "Здорове харчування та спосіб життя ": "health",
    "Канцелярія": "other",
    "Одяг та взуття": "other",
    "Цигарки, стіки, аксесуари": "other",
    "Знижко-Звичка": "other",
    "Каталог Вигідних пропозицій": "other",
    # Sub-level parents
    "Догляд за волоссям": "hygiene",
    "Засоби для фарбування волосся": "hygiene",
    "Аксесуари для волосся": "hygiene",
    "Стайлінг для волосся": "hygiene",
    "Догляд за тілом": "hygiene",
    "Догляд за ротовою порожниною": "hygiene",
    "Дезодорант та антиперспірант": "hygiene",
    "Засоби для гоління і депіляції": "hygiene",
    "Засоби для інтимної гігієни": "hygiene",
    "Мило": "hygiene",
    "Догляд за обличчям": "hygiene",
    "Сонцезахисні засоби": "hygiene",
    "Паперові вироби для гігієни": "hygiene",
    "Косметика та парфумерія": "hygiene",
    "Догляд за руками та нігтями": "hygiene",
    "Догляд за ступнями і ногами": "hygiene",
    "Засоби для прання": "household",
    "Засоби для прибирання": "household",
    "Засоби для миття посуду": "household",
    "Товари для прибирання": "household",
    "Освіжувачі повітря": "household",
    "Освіжувач повітря": "household",
    "Інсектициди": "household",
    "Засоби для взуття і тканин": "household",
    "Зберігання та догляд за одягом": "household",
    "Міцний алкоголь": "alcohol",
    "Вино": "alcohol",
    "Шампанське та ігристе вино": "alcohol",
    "Пиво": "alcohol",
    "Сидр і слабоалкогольні напої": "alcohol",
    "Лікер та бальзам": "alcohol",
    "Лікер та Бальзам": "alcohol",
    "Сир": "dairy",
    "Сир кисломолочний": "dairy",
    "Молоко": "dairy",
    "Вершки": "dairy",
    "Масло і маргарин": "dairy",
    "Йогурт": "dairy",
    "Кисломолочні напої": "dairy",
    "Яйця": "dairy",
    "Десерти, пудинги, коктейлі": "dairy",
    "Ковбаса і сосиски": "meat",
    "Свіже м'ясо": "meat",
    "М'ясні вироби": "meat",
    "Паштет": "meat",
    "М'ясні напівфабрикати": "meat",
    "Посуд для сервірування столу": "kitchen",
    "Посуд для приготування": "kitchen",
    "Кухонне приладдя": "kitchen",
    "Одноразовий посуд": "kitchen",
    "Посуд для зберігання продуктів": "home",
    "Харчова упаковка": "home",
    "Паперові вироби для дому": "home",
    "Паперові вироби": "home",
    "Домашній текстиль": "home",
    "Інтер'єр": "home",
    "Освітлення ": "home",
    "Дрібниці для дому": "home",
    "Побутова техніка": "home",
    "Іграшки": "kids",
    "Догляд за дитиною": "kids",
    "Дитяче харчування": "kids",
    "Корм для котів": "pets",
    "Корм для кошенят": "pets",
    "Корм для собак": "pets",
    "Догляд за тваринами": "pets",
    "Туалетний папір": "home",
    "Цукерки": "sweets",
    "Батончики": "sweets",
    "Східні солодощі": "sweets",
    "Джем, варення, повидло": "sweets",
    "Сушки і сухарі": "snacks",
    "Чай": "hot_drinks",
    "Кава": "hot_drinks",
    "Приправи і спеції": "sauces",
    "Соуси, маринади": "sauces",
    "Соус": "sauces",
    "Майонез та майонезні соуси": "sauces",
    "Гірчиця та хрін": "sauces",
    "Топінги та сиропи": "sauces",
    "Овочева консервація": "canned",
    "Фруктова консервація": "canned",
    "Рибна консервація": "canned",
    "М'ясна консервація": "canned",
    "Морська капуста та водорості": "canned",
    "Оливки та маслини": "canned",
    "Крупа": "grocery",
    "Макаронні вироби": "grocery",
    "Сухі сніданки та пластівці": "grocery",
    "Сухі сніданки та пластівці ": "grocery",
    "Олія": "grocery",
    "Оцет": "grocery",
    "Цукор та цукрозамінники": "grocery",
    "Сіль": "grocery",
    "Дріжджі": "grocery",
    "Їжа швидкого приготування": "grocery",
    "Смаки Азії": "grocery",
    "Для випічки та десертів": "grocery",
    "Сік": "drinks",
    "Квас": "drinks",
    "Мінеральна вода": "drinks",
    "Овочі": "fruits",
    "Фрукти": "fruits",
    "Зелень": "fruits",
    "Гриби": "fruits",
    "Горіхи": "snacks",
    "Сухофрукти": "snacks",
    "Риба приготована ": "fish",
    "Заморожені морепродукти": "fish",
    "Морепродукти": "fish",
    "Крабові палички": "fish",
    "Крабові палички ": "fish",
    "Ікра": "fish",
    "Напівфабрикати та страви заморожені": "frozen",
    "Заморожені напівфабрикати та страви ": "frozen",
    "Напівфабрикати": "frozen",
    "Власна пекарня": "bakery",
    "Хлібобулочні вироби": "bakery",
    "Булочки та здобні вироби": "bakery",
    "Власна кондитерська": "bakery",
    "Тісто": "bakery",
    "Туризм та кемпінг": "hobby",
    "Товари для відпочинку на воді ": "hobby",
    "Товари для барбекю": "hobby",
    "Дача, сад, город": "hobby",
    "Дача, сад та город": "hobby",
    "Письмове приладдя": "hobby",
    "Шкільне приладдя і творчість": "hobby",
    "Товари для подорожей": "hobby",
    "Товари для подорожей ": "hobby",
    "Книги": "hobby",
    "Товари для свята": "hobby",
    "Галантерея": "other",
    "Автотовари": "other",
    "Спортивне харчування": "health",
    "Домашня аптечка": "health",
}


_VARUS_MAP = {
    "52876": "grocery",      # Бакалія
    "53297": "alcohol",      # Алкоголь
    "53036": "dairy",        # Молочні продукти та яйця
    "53028": "meat",         # М'ясо та напівфабрикати
    "53253": "fruits",       # Фрукти, овочі, горіхи
    "53273": "bakery",       # Хлібобулочні вироби
    "52962": "frozen",       # Заморожені продукти
    "58295": "canned",       # Консервація та соління
    "52971": "sweets",       # Кондитерські вироби та солодощі
    "52922": "snacks",       # Снеки
    "52905": "hot_drinks",   # Чай, кава, гарячі напої
    "52956": "drinks",       # Вода, соки, напої
    "52981": "hygiene",      # Гігієна та догляд
    "53168": "household",    # Побутова хімія
    "53085": "home",         # Товари для дому
    "53244": "pets",         # Товари для тварин
    "57351": "bakery",       # Власна випічка та десерти VARUS
}


# ATB: catalog slug → unified slug (direct dict, like Silpo/Varus)
_ATB_MAP = {
    "285-bakaliya": "grocery", "286-kava-kakao": "hot_drinks",
    "287-ovochi-ta-frukti": "fruits", "288-frukti-yagodi": "fruits", "289-ovochi": "fruits",
    "290-gigiena-i-kosmetika": "hygiene", "291-tualetniy-papir": "household",
    "292-alkogol-i-tyutyun": "alcohol", "294-napoi-bezalkogol-ni": "drinks",
    "296-gorilka": "alcohol", "298-gribi": "fruits", "299-konditers-ki-virobi": "sweets",
    "300-skhidni-solodoshchi": "sweets", "301-zhuval-ni-gumki": "sweets",
    "302-zasobi-dlya-golinnya": "hygiene", "303-shokolad": "sweets",
    "305-pripravi-ta-marinadi": "sauces", "306-tovari-dlya-vipichki": "grocery",
    "307-napoi": "drinks", "308-pobutova-khimiya-ta-neprodovol-chi-tovari": "household",
    "309-osvizhuvachi-povitrya": "household", "310-pivo": "alcohol",
    "311-gigienichni-prokladki-tamponi": "hygiene", "312-tsukor": "grocery",
    "313-zasobi-dlya-mittya-posudu": "household",
    "314-pral-ni-poroshki-ta-zasobi-dlya-prannya": "household",
    "316-kislomolochni-napoi": "dairy", "317-sirki-glazurovani": "dairy", "318-chay": "hot_drinks",
    "320-vino": "alcohol", "321-tsukerki": "sweets", "322-zamorozheni-produkti": "frozen",
    "324-soki-nektari": "drinks", "325-khlibobulochni-virobi": "bakery",
    "326-bulochni-listkovi-virobi": "bakery", "327-batonchiki": "sweets",
    "329-smetana": "dairy", "331-khlib": "bakery", "333-baton": "bakery",
    "334-morozivo": "frozen", "335-dezodoranti": "hygiene", "336-inshiy-alkogol": "alcohol",
    "337-likeri-nastoyanki-bal-zami": "alcohol", "338-vafli": "sweets",
    "339-dityache-kharchuvannya": "kids", "340-pyure": "kids", "341-boroshno": "grocery",
    "344-m-yaso-okholodzhene": "meat", "345-shampuni": "hygiene", "347-khlibtsi": "snacks",
    "348-makaronni-virobi": "grocery", "349-yogurti": "dairy", "350-kon-yak": "alcohol",
    "351-torti-i-tistechka": "bakery", "353-riba-i-moreprodukti": "fish",
    "356-vareniki-pel-meni-mlintsi": "frozen", "358-tovari-dlya-domu": "home",
    "359-yelektrolampi": "home", "360-kovbasa-i-m-yasni-delikatesi": "meat",
    "363-sirniki-zapal-nichki": "household", "364-yenergetichni": "drinks",
    "365-sousi-ketchupi": "sauces", "366-molochni-sumishi": "kids", "367-voda": "drinks",
    "368-soki-chay": "drinks", "369-odnorazoviy-posud": "kitchen",
    "370-zasobi-po-doglyadu-za-vzuttyam": "household",
    "371-diabetichna-ta-dietichna-produktsiya": "health",
    "372-pidguzki-dlya-doroslikh": "health", "373-tovari-dlya-ditey": "kids",
    "374-pidguzki-pelyushki": "kids", "375-paketi-dlya-pokupok": "household",
    "376-prezervativi": "health", "377-sosiski-sardel-ki": "meat",
    "378-sukhi-snidanki": "grocery", "379-sir-kislomolochniy": "dairy",
    "380-sirki-dityachi": "dairy", "381-yaytsya-kuryachi-perepelini": "dairy",
    "382-molochni-deserti": "dairy", "383-batareyki": "home", "384-medikamenti": "health",
    "386-kashi": "grocery", "387-doglyad-za-tilom": "hygiene",
    "389-kantselyars-ki-tovari": "hobby", "390-zelen": "fruits",
    "392-tovari-dlya-pribirannya": "household", "394-tovari-dlya-kukhni": "kitchen",
    "395-krupi": "grocery", "397-lavash": "bakery", "398-moloko": "dairy",
    "399-vershki": "dairy", "400-sad-ta-gorod": "home", "402-siri-m-yaki": "dairy",
    "404-zasobi-proti-komakh": "household", "405-mebli": "home",
    "406-krabovi-palichki": "fish", "408-inshi-m-yasni-virobi": "meat",
    "409-krekeri": "snacks", "410-posud-i-aksesuari-dlya-kukhni": "kitchen",
    "411-knizhki": "hobby", "412-gospodars-ki-tovari": "household",
    "414-maslo-i-margarin": "dairy", "415-yapons-ka-kukhnya": "other",
    "416-vasabi-imbir-otset": "sauces", "417-odyag-vzuttya-ta-aksesuari": "other",
    "418-dityache-pechivo": "kids", "420-tovari-dlya-vipichki-i-upakovki-izhi": "kitchen",
    "421-m-yasni-napivfabrikati": "meat", "422-dityacha-molochna-produktsiya": "kids",
    "423-servetki-rushniki": "household", "424-dityachi-igrashki": "kids",
    "429-budivnitstvo-remont-instrumenti": "home", "430-tisto-vipichka-pitsa": "frozen",
    "431-mayonez": "sauces", "433-siri-tverdi": "dairy", "436-tovari-dlya-tvarin": "pets",
    "437-korm": "pets", "439-siri-plavleni": "dairy", "440-preservi": "fish",
    "441-ribna-narizka": "fish", "443-krasa-i-zdorov-ya": "health",
    "444-buterbrodni-masla-zakuski-pasti": "grocery", "446-gorikhi-sukhofrukti": "snacks",
    "449-napovnyuvach": "pets", "450-servetki-vologi": "hygiene",
    "452-ovochi-ta-frukti-svizhozamorozheni": "frozen", "454-sontsezakhisna-seriya": "hygiene",
    "455-paketi-dlya-smittya": "household", "457-napivfabrikati": "frozen",
    "458-kolgoti-gol-fi-shkarpetki": "other", "460-dekor-i-inter-er": "home",
    "464-nori-i-panirovka": "grocery", "465-vse-dlya-kempingu": "hobby",
    "467-galantereya": "other", "468-solinnya-salati": "canned",
    "473-vatni-palichki-diski": "hygiene", "474-kantstovari": "hobby",
    "478-mobil-niy-zv-yazok": "home", "479-tyutyunovi-virobi": "tobacco",
    "482-garyacha-vipichka": "bakery", "483-ruchki-olivtsi-flomasteri": "hobby",
    "485-mul-timedia-i-aksesuari": "home", "488-khobbi-ta-sport": "hobby",
    "489-drugi-stravi": "other", "490-drazhe": "sweets", "495-kemping": "hobby",
    "502-kulinariya": "other", "503-buterbrodi-burgeri": "other",
}


# Auchan: level-3 url_key → unified slug (direct dict, like Silpo/Varus/ATB)
_AUCHAN_MAP = {
    # Продукти харчування
    "bakaleya": "grocery", "konservirovannoe": "canned", "sladosti": "sweets",
    "sneki": "snacks", "molochnye-produkty-i-jajca": "dairy", "voda-i-napitki": "drinks",
    "ovoschi-frukty-i-griby": "snacks",  # Сухофрукти та горіхи
    "gorjachie-napitki": "hot_drinks", "tovary-mira": "grocery", "organika": "grocery",
    "zdorovoe-pitanie": "grocery",
    # Алкогольні напої
    "krepkie-napitki": "alcohol", "vino": "alcohol", "pivo-i-sidr": "alcohol",
    "likery-i-aperitivy": "alcohol",
    # Тютюнові вироби
    "sigarety": "tobacco", "sigary-i-sigarilly": "tobacco", "tabak": "tobacco",
    "stiki-dlja-sistem-nagrevanija": "tobacco",
    "aksessuary-dlja-sigaret-i-samokrutok": "tobacco", "jelektronnye-sigarety": "tobacco",
    "zazhigalki-spichki": "household",
    # Побутова техніка
    "krupnaja-bytovaja-tehnika": "home", "tovary-dlja-lichnogo-uhoda": "hygiene",
    "tehnika-dlja-prigotovlenija-pischi": "kitchen", "tehnika-dlja-uhoda-za-domom": "home",
    "vstraivaemaja-tehnika": "home", "klimaticheskaja-tehnika": "home",
    "nabory-dlja-manikjura-i-pedikjura": "hygiene", "medicinskie-pribory": "health",
    "shvejnye-mashiny-i-overloki": "home",
    # Електроніка
    "al-ternativni-dzherela-zhivlennja": "home", "komp-juternaja-tehnika": "home",
    "komp-juternye-kabeli-i-perehodniki": "home", "komp-juternaja-pereferija": "home",
    "setevoe-oborudovanie": "home", "tovary-dlja-gejmerov": "home", "smart-gadzhety": "home",
    "telefony": "home", "audiotehnika": "home", "televizory-i-aksessuary": "home",
    "fototehnika-i-aksessuary": "home", "orgtehnika": "home", "jelektrotransport": "home",
    "muzykal-nye-instrumenty": "home", "noutbuki": "home",
    # Товари для дому
    "kuhnja": "kitchen", "osveschenie": "home", "tekstil-dlja-doma": "home",
    "stil-tvoego-doma": "home", "vannaja-komnata": "home", "mebel-dlja-doma": "home",
    "uborka-i-uhod-po-domu": "household", "inter-er-dlja-doma": "home",
    # Побутова хімія
    "sredstva-dlja-stirki": "household", "sredstva-dlja-myt-ja-posudy": "household",
    "sredstva-dlja-posudomoechnyh-mashin": "household", "sredstva-dlja-uborki": "household",
    "sredstva-zaschity-ot-nasekomyh-i-vreditelej": "household",
    "aksessuary-dlja-uborki": "household", "bumazhnye-izdelija-dlja-doma": "household",
    "pischevaja-upakovka": "kitchen", "uhod-za-obuv-ju": "household",
    "sredstva-po-uhodu-za-odezhdoj": "household",
    # Іграшки
    "brendy": "kids", "personazhi": "kids", "igrovye-figurki": "kids",
    "nastol-nye-igry": "kids", "detskie-konstruktory": "kids", "mashinki-i-tehnika": "kids",
    "detskoe-oruzhie": "kids", "detskie-kukly": "kids", "detskie-roboty": "kids",
    "igrushki-dlja-malyshej": "kids", "razvivayuschie-igry": "kids",
    "detskie-igrushki-dlja-otkrytogo-vozduha": "kids", "detskie-igrovye-nabory": "kids",
    "mjagkie-igrushki": "kids", "naduvnye-igrushki": "kids", "tovary-dlja-prazdnika": "kids",
    # Все для немовлят
    "detskoe-pitanie": "kids", "tovary-dlja-kupanija": "kids", "detskaja-gigiena-i-uhod": "kids",
    "inter-er-dlja-detskoj-komnaty": "kids", "tovary-dlja-kormlenija": "kids",
    "vse-dlja-mam": "kids", "koljaski-dlja-detej": "kids", "bezopasnost-malyshej": "kids",
    "slingy-rjukzaky-perenosky": "kids",
    # Спорт і відпочинок
    "velotovary": "hobby", "tovary-dlja-igrovyh-vidov-sporta": "hobby",
    "turisticheskie-tovary": "hobby", "tovary-dlja-rybalki": "hobby",
    "aksessuary-dlja-bani-i-sauny": "hobby", "roliki-skejtbordy-samokaty": "hobby",
    "boevye-iskusstva-i-edinoborstva": "hobby", "tjazhelaja-atletika": "hobby",
    "sportivnye-fiksatory-i-supporty": "hobby", "trenazhery": "hobby",
    "tovary-dlja-fitnesa": "hobby", "tovary-dlja-zimnego-sporta": "hobby",
    "vodnye-vidy-sporta": "hobby", "aksessuary-dlja-sporta-i-otdyha": "hobby",
    # Все для тварин
    "korm-dlja-zhivotnyh": "pets", "gigiena-i-uhod-dlja-zhivotnyh": "pets",
    "igrushki-dlja-zhivotnyh": "pets", "aksessuary-dlja-zhivotnyh": "pets",
    "odezhda-dlja-zhivotnyh": "pets", "miski-dlja-koshek": "pets",
    "akvariumy-i-terrariumy": "pets",
    # Все для подорожей
    "chemodany": "hobby", "sumki-dorozhnye": "hobby", "rjukzaky": "hobby",
    "bagazh-dlja-detej": "hobby", "bagazhnye-aksessuary": "hobby",
    # Косметика
    "sredstva-po-uhodu-za-telom": "hygiene", "sredstva-dlja-lica": "hygiene",
    "uhod-za-volosami": "hygiene", "dekorativnaja-kosmetika": "hygiene",
    "parfjumerija": "hygiene", "kosmeticheskie-podarochnye-nabory": "hygiene",
    "sredstva-lichnoj-gigieny": "hygiene", "kosmetika-dlja-muzhchin": "hygiene",
    "intimnye-sredstva": "health", "parafarmacevtika": "health",
    "kosmetika-dlja-detej": "hygiene", "sumki-i-kosmetichki": "hygiene",
    "kosmetika-dlja-mam": "hygiene", "bodiart": "hygiene",
    # Подарунки
    "podarunki-dlja-nei": "other", "podarunki-dlja-n-ogo": "other",
    "podarunki-avtomobilistu": "other", "podarunki-dlja-ditej": "kids",
    "podarunki-dlja-gejmeriv": "other", "podarunkovi-nabori": "other",
    "podarunki-na-novosillja": "other",
    # БАДи
    "vitamini-za-simptomami": "health", "vitamini": "health", "rib-jachij-zhir-i-masla": "health",
    "minerali": "health", "antioksidanti": "health", "superfud": "health",
    "inshi-dobavki-aksesuari": "health",
    # Одяг
    "zhenskaja-odezhda": "other", "muzhskaja-odezhda": "other", "detskaja-odezhda": "kids",
    "odezhda-dlja-malyshej": "kids", "aksessuary-odezhda": "other", "obuv": "other",
    # Канцтовари та книги
    "knigi": "hobby", "uchebnaja-literatura": "hobby", "kanceljarskie-tovary": "hobby",
    "tovary-dlja-tvorchestva": "hobby", "ofisnye-prinadlezhnosti": "hobby",
    "tovary-dlja-podarkov": "other", "rjukzaki-i-rancy": "hobby",
    "kollekcii-kanctovarov": "hobby",
    # Сад, город, дача
    "sadovaja-tehnika": "home", "otdyh-na-otkrytom-vozduhe": "hobby",
    "komnatnye-rastenija": "home", "sadovyj-poliv": "home", "ruchnoj-sadovyj-inventar": "home",
    "sadovye-aksessuary": "home", "sadovyj-inventar": "home", "obuv-dlja-sada": "home",
    "iskusstvennye-cvety": "home", "kaminy-pechi": "home",
    # Розумний дім
    "umnaja-bytovaja-tehnika": "home", "umnaja-klimaticheskaja-tehnika": "home",
    "sistemy-umnogo-doma": "home", "rozetki": "home", "upravlenie-jelektropriborami": "home",
    "videonabljudenie": "home",
    # Автомобільні товари
    "avtohimija": "other", "tehpomosch": "other", "akkumuljatoru": "other",
    "masla-dlja-avtomobilja": "other", "shini": "other", "jelektrooborudovanie-i-svet": "other",
    "avtomobil-nye-aksessuary": "other", "zapasnye-chasti": "other", "avtozvuk": "other",
    # Товари для ремонту
    "instrumentu-dlja-remonta": "home", "stroitel-nye-kreplenija": "home",
    "otdelochnye-materialy": "home", "oborudovanie-jelektricheskoe": "home",
    "santehnika": "home", "bezopasnost-doma": "home",
}


def map_auchan_category(slug: str) -> str:
    return _AUCHAN_MAP.get(slug, "other")


def map_atb_category(slug: str) -> str:
    return _ATB_MAP.get(slug, "other")


def map_silpo_category(slug: str) -> str:
    return _SILPO_MAP.get(slug, "other")


def map_varus_category(slug: str) -> str:
    return _VARUS_MAP.get(slug, "other")


# Novus department id (Magento category id) -> unified slug. A product's
# category_slug is the numeric top department id, which is far more stable than
# the titles (the old title map matched almost nothing — see git history).
_NOVUS_DEPT = {
    "109": "kids",       # Товари для дітей
    "110": "alcohol",    # Алкоголь
    "111": "grocery",    # Бакалія
    "112": "fish",       # Риба/морепродукти
    "113": "dairy",      # Молочна продукція/Яйця
    "114": "hygiene",    # Непродовольчі товари (shampoo/cosmetics/household)
    "115": "sweets",     # Кондитерські вироби
    "116": "bakery",     # Випічка
    "117": "fruits",     # Фрукти/овочі
    "118": "meat",       # Гастрономія (deli/sausage)
    "119": "drinks",     # Напої
    "120": "other",      # Кулінарія (prepared food — no unified bucket)
    "121": "meat",       # М'ясо
    "123": "kitchen",    # Посуд
    "124": "household",  # Побутова хімія
}


def map_novus_category(slug: str) -> str:
    return _NOVUS_DEPT.get((slug or "").strip(), "other")


# Fora: top-level category id (str) → unified slug. Products store categories[0].id (top-level).
_FORA_MAP = {
    "3268": "other",       # Піца та кулінарія
    "2790": "fruits",      # Фрукти, овочі та соління
    "2656": "dairy",       # Молочні продукти та яйця
    "2492": "grocery",     # Бакалія, консерви та соуси
    "2738": "meat",        # Ковбаси та м'ясні делікатеси
    "2902": "bakery",      # Хліб та хлібобулочні вироби
    "5358": "bakery",      # Власна випічка
    "5401": "meat",        # Свіже м'ясо
    "2699": "fish",        # Риба
    "5392": "dairy",       # Сири
    "2913": "sweets",      # Солодощі
    "3642": "drinks",      # Мінеральна і питна вода
    "2479": "drinks",      # Соки та напої
    "2451": "alcohol",     # Алкоголь
    "2730": "snacks",      # Снеки
    "2886": "other",       # Сигарети, стіки, жуйки
    "2775": "hot_drinks",  # Кава, чай
    "2686": "frozen",      # Заморожена продукція
    "2943": "hygiene",     # Краса, догляд та гігієна
    "2975": "household",   # Побутова хімія, товари для дому
    "2865": "kids",        # Дитячі товари
    "2892": "home",        # Квіти, товари для саду та городу
    "3060": "pets",        # Товари для тварин
}


def map_fora_category(slug: str) -> str:
    return _FORA_MAP.get(slug, "other")


# Fozzy top-level department slugs (canonical route slugs, see scrapers/fozzy.py).
_FOZZY_MAP = {
    "3643-kulinariya": "other",                            # Кулінарія (готові страви)
    "3644-solodoshchi-sneky": "sweets",                    # Солодощі, снеки
    "3645-tovary-dlya-ditey": "kids",                      # Товари для дітей
    "3646-sousy-spetsiyi-roslynna-oliya": "sauces",        # Соуси, спеції, олія
    "3647-m-yaso-ptytsya": "meat",                         # М'ясо, птиця
    "3648-odyag-vzuttya-aksesuary": "other",               # Одяг, взуття, аксесуари
    "3649-pobutova-tekhnika": "home",                      # Побутова техніка
    "3650-molochna-produktsiya-syr-yaytsya": "dairy",      # Молочна продукція, сир, яйця
    "3651-bezalkogolni-napoyi": "drinks",                  # Безалкогольні напої
    "3652-tovary-dlya-domu-avto": "home",                  # Товари для дому, авто
    "3654-alkogol": "alcohol",                             # Алкоголь
    "3655-zootovary": "pets",                              # Зоотовари
    "3656-zdorove-i-sportyvne-kharchuvannya": "health",    # Здорове і спортивне харчування
    "3657-kosherni-produkty": "other",                     # Кошерні продукти
    "3660-chay-kava": "hot_drinks",                        # Чай, кава
    "3661-zamorozheni-produkty": "frozen",                 # Заморожені продукти
    "3663-krasa-gigiyena": "hygiene",                      # Краса, гігієна
    "3664-khlibobulochni-vyroby": "bakery",                # Хлібобулочні вироби
    "3665-kovbasa-m-yasni-vyroby": "meat",                 # Ковбаса, м'ясні вироби
    "3666-ryba-moreprodukty": "fish",                      # Риба, морепродукти
    "3667-bakaliya-konservatsiya": "grocery",              # Бакалія, консервація
    "3668-ovochi-frukty-gryby": "fruits",                  # Овочі, фрукти, гриби
    "3669-tovary-dlya-dachi-vidpochynku": "hobby",         # Товари для дачі, відпочинку
    "3670-kantstovary-knygy-presa": "hobby",               # Канцтовари, книги, преса
    "3708-aziatska-kukhnya": "other",                      # Азіатська кухня
    "3814-pobutova-khimiya": "household",                  # Побутова хімія
}


def map_fozzy_category(slug: str) -> str:
    return _FOZZY_MAP.get(slug, "other")


# Metro: level-1 department display names (see scrapers/metro.py). Keys use an ASCII
# apostrophe; map_metro_category normalises the curly ’ Metro actually returns.
_METRO_MAP = {
    # Продукти
    "М'ясо та птиця": "meat",
    "Риба та морепродукти": "fish",
    "Молочні продукти та яйця": "dairy",
    "Бакалія": "grocery",
    "Олія, оцет, консерви": "canned",
    "Фрукти та овочі": "fruits",
    "Заморозка": "frozen",
    "Хліб та хлібобулочні вироби": "bakery",
    "Соуси та спеції": "sauces",
    "Алкогольні напої": "alcohol",
    "Холодні напої": "drinks",
    "Гарячі напої": "hot_drinks",
    "Солодощі, чіпси, снеки": "sweets",
    # Непродовольчі товари
    "Побутова хімія": "household",
    "Господарські товари": "home",
    "Кухня та посуд": "kitchen",
    "Інтер'єр, меблі та текстиль": "home",
    "Особиста гігієна та догляд": "hygiene",
    "Канцелярія": "hobby",
    "Хобі та відпочинок": "hobby",
    "Дитяче": "kids",
    "Товари для тварин": "pets",
    "Святкові товари": "home",
    "Побутова техніка": "home",
}


def map_metro_category(slug: str) -> str:
    # Normalise the curly apostrophe (U+2019) / modifier letter (U+02BC) to ASCII.
    key = (slug or "").replace("’", "'").replace("ʼ", "'").strip()
    return _METRO_MAP.get(key, "other")
